[General]
background=wallpapers/cyber_city_stars.jpg
type=image
color=#282828
font="Inter"
fontSize=14
clockColor=#ebdbb2
clockFont="Inter"
clockFontSize=64
dateColor=#a89984
dateFont="Inter"
dateFontSize=24
passwordColor=#ebdbb2
passwordBackground=#3c3836
passwordBorder=#504945
loginColor=#ebdbb2
loginBackground=#3c3836
loginBorder=#504945
